language: node_js

node_js:
    - 'stable'

cache:
    directories:
        - node_modules

install:
    - npm install -g codecov
    - npm install

script:
    - npm run test
    - npm run report-coverage
    - codecov
